
# CLS client-specific configuration
cls.name=CLS Client
cls.message=Hello from CLS centralized configuration for UAT
cls.environment=UAT
cls.organization=GDC
cls.feature.enabled=true

cls.db.username=scribe_uat
cls.db.password={cipher}c9fc8f354d0f63aa00a5f987cb6a4c1d99d9c0d22ff4ecfc8fbc31d192ce5b486798505b66a361e4545e0d63f60042a5