
# CLS client-specific configuration
cls.name=CLS Client
cls.message=Hello from CLS centralized configuration for Development
cls.environment=Development
cls.organization=GDC
cls.feature.enabled=true

cls.db.username=scribe_dev
cls.db.password={cipher}ac3d6fcc10a779e350740a685fd17ff500621ec9b6fe34bb53575c687dcf4a5f1c2b8cf396a31d3aa36168094dd6b9d0
