
# CLS client-specific configuration
cls.name=CLS Client
cls.message=Hello from CLS centralized configuration
cls.environment=Production
cls.organization=GDC
cls.feature.enabled=true

cls.db.username=scribe_prod
cls.db.password={cipher}57cc18a416797c6444c31349b63e5b352b7414937fd304ce904169a43407448ad4de861a7c9c5cde38562a922d7483b8